version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - elasticsearch
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  ml:
    build:
      context: ./cmd/ml
    ports:
      - 8000:8000

  collector:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ELASTIC_ADDR=http://elasticsearch:9200
      - ML_URL=http://ml:8000/predict
      - ELASTIC_INDEX=logs-sentinel
      - LOG_SENTINEL_DIR=/app/logs
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
      - ml
      - prometheus

volumes:
  esdata: 